const categoriesList = [
    { id: '1', name: 'Shopping', icon: 'cart-outline', color: '#FF6B6B',  type: 'expense' },
    { id: '2', name: 'Food', icon: 'restaurant-outline', color: '#4ECDC4',  type: 'expense'  },
    { id: '3', name: 'Transport', icon: 'car-outline', color: '#45B7D1',  type: 'expense'  },
    { id: '4', name: 'Entertainment', icon: 'film-outline', color: '#96CEB4',  type: 'expense'  },
    { id: '5', name: 'Income', icon: 'cash-outline', color: '#2ECC71',  type: 'expense'  },
    { id: '6', name: 'Health', icon: 'medkit-outline', color: '#FF5733',  type: 'expense'  },
    { id: '7', name: 'Utilities', icon: 'flash-outline', color: '#F39C12',  type: 'expense'  },
    { id: '8', name: 'Education', icon: 'book-outline', color: '#8E44AD',  type: 'expense'  },
    { id: '9', name: 'Gifts', icon: 'gift-outline', color: '#C0392B',  type: 'expense'  },
    { id: '10', name: 'Travel', icon: 'airplane-outline', color: '#3498DB',  type: 'expense'  },
    { id: '11', name: 'Savings', icon: 'piggy-bank-outline', color: '#2E86C1',  type: 'expense'  },
    { id: '12', name: 'Clothing', icon: 'shirt-outline', color: '#1ABC9C',  type: 'expense'  },
    { id: '13', name: 'Charity', icon: 'heart-outline', color: '#E74C3C',  type: 'expense'  },
    { id: '14', name: 'Fitness', icon: 'barbell-outline', color: '#27AE60',  type: 'expense'  },
    { id: '15', name: 'Insurance', icon: 'shield-outline', color: '#34495E',  type: 'expense'  },
    { id: '16', name: 'Pets', icon: 'paw-outline', color: '#F5B041',  type: 'expense'  },
    { id: '17', name: 'Home', icon: 'home-outline', color: '#D35400',  type: 'expense'  },
    { id: '18', name: 'Tech', icon: 'laptop-outline', color: '#2980B9',  type: 'expense'  },
    { id: '19', name: 'Hobbies', icon: 'brush-outline', color: '#9B59B6',  type: 'expense'  },
    { id: '20', name: 'Miscellaneous', icon: 'help-circle-outline', color: '#BDC3C7',  type: 'expense'  },
    { id: '21', name: 'Salary', icon: 'cash-outline', color: '#2ECC71', type: 'income' },
    { id: '22', name: 'Business', icon: 'briefcase-outline', color: '#2980B9', type: 'income' },
    { id: '23', name: 'Investments', icon: 'trending-up-outline', color: '#F1C40F', type: 'income' },
    { id: '24', name: 'Gifts', icon: 'gift-outline', color: '#E91E63', type: 'income' },
    { id: '25', name: 'Other Income', icon: 'help-circle-outline', color: '#BDC3C7', type: 'income' },
];


export default categoriesList;
